language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip install pytest python-socketio pylint psycopg2 tornado eventlet

script:
  - sudo python -m pytest .
  - cd server
  - pylint -E *.py
