language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - npm install -g jasmine
  - npm install -g protractor
  - pip install -r requirements.txt

  - cd 2D\ Simulation
  - npm install
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - createdb
  - psql -f server/create-baseline.sql -U postgres
  - npx webdriver-manager update --standalone
  - npx webdriver-manager status
  - npx webdriver-manager start &
  - sleep 5

script:
  - cd server
  - python -m pytest . --ignore=rhit-xprize-neural-network
  - python simulation.py &
  - sleep 10
  - cd ../2D\ Simulation
  - npx jasmine
  - python -m http.server &
  - sleep 10
  - echo > /dev/tcp/localhost/8080
  - npx protractor conf.js
  - sleep 10
  - echo > /dev/tcp/localhost/8080
