language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip3 install -r requirements.txt

script:
  - python3 -m pylint --version
  - cd server
  - python3 -m pytest . --ignore=rhit-xprize-neural-network
  - python3 -m pylint -E *.py
