language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip install -r requirements.txt

script:
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd server
  - pylint -E *.py
