language: python
python:
  - "3.6"

cache:
  directories:
    - node_modules

services:
  - postgresql

install:
  - ./install.sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - createdb
  - psql -f server/create-baseline.sql -U postgres

script:
  - ./test.sh
