language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip install -r requirements.txt

script:
  - python -m pylint --version
  - cd server
  - python -m pytest . --ignore=rhit-xprize-neural-network
  - pythin -m pylint -E *.py
