language: python
sudo: enabled
python:
  - "3.6"

services:
  - postgresql

install:
  - npm install jasmine
  - npm install protractor
  - sudo pip install -r requirements.txt  

before_script:
  - psql -f server/create-baseline.sql -U postgres
  - node_modules/protractor/bin/webdriver-manager update --standalone --chrome
  - node_modules/protractor/bin/webdriver-manager start &
  - sleep 5

script:
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - python3 simulation.py &
  - cd ../2D\ Simulation
  - npx jasmine
  - python3 -m http.server &
  - sleep 5
  - xvfb-run npx protractor conf.js
