language: python
sudo: enabled
python:
  - "3.6"

install:
  - npm install jasmine
  - npm install protractor
  - sudo pip install -r requirements.txt  
  
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npx webdriver-manager update
  - npx webdriver-manager start &
  - sleep 5
  
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd ../2D\ Simulation
  - npx jasmine
  - npx protractor conf.js
