language: python
python:
  - "3.6"

cache:
  directories:
    - node_modules

services:
  - postgresql

install:
  - pip install -r requirements.txt

  - cd 2D\ Simulation
  - npm install
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - createdb
  - psql -f server/create-baseline.sql -U postgres
  - npm install protractor

  # Normally, we'd call:

  # - node_modules/protractor/bin/webdriver-manager update --standalone

  # here, but the geckodriver (the one that is used by Firefox) gets
  # pulled directly from GitHub on each build, and eventually we hit
  # the rate limit. As such, it is currently set up on travis to cache
  # the node_modules folder (see above) where the driver can live in
  # between builds. IF the cache is ever corrupted, out of date, or
  # deleted, put the update line back for a run or two just to put the
  # driver back into cache.

  # Similarly, we need to touch the (already existing) file to ensure
  # it's date of creation was withing the last hour so as not to ping
  # GitHub (https://github.com/angular/webdriver-manager/issues/270).
  - touch node_modules/protractor/node_modules/webdriver-manager/selenium/update-config.json
  - node_modules/protractor/bin/webdriver-manager status
  - node_modules/protractor/bin/webdriver-manager start &
  - sleep 5

script:
  - cd server
  - python -m pytest . --ignore=rhit-xprize-neural-network
  - python simulation.py &
  - sleep 10

  - cd ../2D\ Simulation
  - npx jasmine
  - python -m http.server &
  - sleep 10

  - npx protractor conf.js
