language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo pip install -r requirements.txt
  - npm install jasmine

script:
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd ../2D\ Simulation
  - jasmine
