language: python
sudo: enabled
python:
  - "3.6"

install:
  - npm install jasmine
  - sudo pip install -r requirements.txt

script:
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd ../2D\ Simulation
  - npx jasmine
