language: python
sudo: enabled
python:
  - "3.6"

install:
  - npm install jasmine
  - npm install protractor
  - sudo pip install -r requirements.txt
  - ./nodemodules/protractor/bin/webdriver-manager update
  
beforescript:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5
  
script:
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd ../2D\ Simulation
  - npx jasmine
  - npx protractor conf.js
