language: python
sudo: enabled
python:
  - "3.6"

install:
  - sudo apt remove pylint
  - sudo pip install -r requirements.txt

script:
  - pylint --version
  - cd server
  - python3 -m pytest . --ignore=rhit-xprize-neural-network
  - pylint -E *.py
